### ISSUE TITLE
Rotate images

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/image-lambda#2]
Images that contain rotation meta data (e.g. from phones) should be rotated in the right direction.

**Comment by quite** [comment]
I attempted to do this, and found a function ready in Pillow. And could simplify the resizing as well (but it no longer scales up, OK?).

**But**, when trying this on a photo I just shot with my phone camera, Pillow just crashes on that image. Stumped. So, catch all exceptions as well huh..

**Comment by quite** [comment]
#3

**Comment by rotsee** [comment]
fixed with https://github.com/fruktkartan/image-lambda/pull/3
