### ISSUE TITLE
images in s3 have content-type: binary/octet-stream

### ISSUE THREAD

**Issue by quite** [fruktkartan/image-lambda#6]
Would be nice if they could have correct image/* Then I could just link to images in fruktsam :) As it stands, browser offers to download the images. But there are workarounds for that...

**Comment by quite** [comment]
Aaaa! Easy since it's only the images we generate ourselves!

**Comment by quite** [comment]
Would you have a look at this @rotsee ? Would be nice if at least the images we have processed, and know are jpegs, become `image/jpeg`. 

When it's done, all existing images can be fixed somehow... https://stackoverflow.com/questions/41015200/how-to-change-content-type-of-amazon-s3-objects

**Comment by rotsee** [comment]
Oh, sorry for losing track of this. Will fix!

**Comment by rotsee** [comment]
From now on, all images will have the right content-type (and also a cache control header). Existing images are being updates in this very moment.
